import React,{useState} from "react";
import {ArrowRight,CalendarDays,CheckCircle2,ChevronRight,Gamepad2,Globe2,Menu,MessageCircle,Pencil,Play,Plus,Swords,Trash2,Trophy,Users,X,Youtube,Github,BarChart3,LockKeyhole,ClipboardList} from "lucide-react";
import {Link} from "react-router-dom";

const YT="https://www.youtube.com/@techgurusumit1";
const GAMES=[["Asphalt Legends","Primary racing content","🏎️"],["Subway Surfers","Fast-paced runs & shorts","🚇"],["Hill Climb Racing","Challenge runs","🚙"],["Temple Run","Endless-run gaming","🗿"],["Roblox","Community gameplay","🧱"],["Minecraft","Builds & adventures","⛏️"]];
const FORMATS=["Round Robin","Single Elimination","Double Elimination","3 Game Guarantee","Swiss System","League (Season Format)"];
const SEED=[
{id:1,name:"TGS Clash #2",game:"Asphalt Legends",format:"Single Elimination",players:["Sawan","Aman","Rohit","Karan"],date:"13 Sep 2026",status:"Completed",passwordEnabled:false,password:"",fixtures:[]},
{id:2,name:"Death Race: Chapter 4",game:"Asphalt Legends",format:"Single Elimination",players:["Player 1","Player 2","Player 3","Player 4"],date:"09 Aug 2026",status:"Completed",passwordEnabled:false,password:"",fixtures:[]},
{id:3,name:"TGS Community Cup",game:"Subway Surfers",format:"League (Season Format)",players:["Player 1","Player 2","Player 3","Player 4"],date:"20 Sep 2026",status:"Upcoming",passwordEnabled:false,password:"",fixtures:[]}
];
function clean(a){return a.map(x=>x.trim()).filter(Boolean)}
function nextPow(n){let x=2;while(x<n)x*=2;return x}
function roundLabel(size,i){const l=size/Math.pow(2,i);if(l===2)return"Final";if(l===4)return"SF";if(l===8)return"QF";return"R"+l}
function circle(names,count){const a=names.slice();if(a.length%2)a.push("");const total=a.length;let cur=a.map((_,i)=>i),out=[];for(let r=0;r<(count||Math.max(1,total-1));r++){const pairs=[];for(let i=0;i<total/2;i++){const x=cur[i],y=cur[total-1-i];if(a[x]&&a[y])pairs.push([a[x],a[y]])}out.push(pairs);cur=[cur[0],cur[total-1],...cur.slice(1,total-1)]}return out}
function makeFixtures(format,names){const n=clean(names),id=()=>Date.now()+Math.random(),out=[];
if(format==="Round Robin"||format==="League (Season Format)"){const rs=circle(n);rs.forEach((r,ri)=>r.forEach(([a,b],p)=>out.push({id:id(),round:ri,roundLabel:(format==="League (Season Format)"?"Season R":"Round ")+(ri+1),position:p,p1:a,p2:b,winner:""})));if(format==="League (Season Format)"){const off=rs.length;rs.forEach((r,ri)=>r.forEach(([a,b],p)=>out.push({id:id(),round:off+ri,roundLabel:"Season R"+(off+ri+1),position:p,p1:b,p2:a,winner:""})))}return out}
if(format==="3 Game Guarantee"){const rs=circle(n,Math.max(3,Math.min(5,n.length<4?5:3)));rs.forEach((r,ri)=>r.forEach(([a,b],p)=>out.push({id:id(),round:ri,roundLabel:"Guarantee R"+(ri+1),position:p,p1:a,p2:b,winner:""})));return out}
if(format==="Swiss System"){return(circle(n,1)[0]||[]).map(([a,b],p)=>({id:id(),round:0,roundLabel:"Swiss R1",position:p,p1:a,p2:b,winner:""}))}
const size=nextPow(Math.max(2,n.length)),matches=size/2,byes=size-n.length;let c=0;const rounds=[[]];
for(let p=0;p<matches;p++){let a=n[c++],b;if(p>=byes)b=n[c++];rounds[0].push({id:id(),round:0,roundLabel:roundLabel(size,0),position:p,p1:a,p2:b,winner:b?"":a})}
for(let r=1;r<Math.log2(size);r++){const count=size/Math.pow(2,r+1);rounds[r]=[];for(let p=0;p<count;p++)rounds[r].push({id:id(),round:r,roundLabel:roundLabel(size,r),position:p,p1:"",p2:"",winner:""})}return rounds.flat()}
function status(s){return s.toLowerCase().replaceAll(" ","-")}

function Home(){const[mob,setMob]=useState(false);return <div className="site"><header className="nav">
<Link to="/" className="brand"><span className="brand-badge">TGS</span><span><b>Tech Guru Sumit</b><small>Gaming • Tournaments • Community</small></span></Link>
<nav className={mob?"nav-links open":"nav-links"}><a href="#home">Home</a><a href="#games">Games</a><Link to="/tournaments">Tournament Manager</Link><a href="#community">Community</a><a href="#about">About</a></nav>
<div className="nav-actions"><a className="icon-link" href={YT} target="_blank" rel="noreferrer"><Youtube size={18}/></a><a className="subscribe" href={YT} target="_blank" rel="noreferrer">Subscribe <ArrowRight size={15}/></a><button className="mobile-menu" onClick={()=>setMob(!mob)}>{mob?<X/>:<Menu/>}</button></div></header>
<section className="hero" id="home"><div className="hero-grid"/><div className="hero-copy"><span className="eyebrow"><span className="pulse"/> TGS GAMING HUB</span><h1>PLAY. RACE.<br/><span>CONQUER.</span></h1><p>Gaming videos, live streams, community tournaments and competitive racing action from Tech Guru Sumit.</p><div className="hero-cta"><a className="primary" href={YT} target="_blank" rel="noreferrer"><Play size={17} fill="currentColor"/> Watch on YouTube</a><Link className="secondary" to="/tournaments"><Trophy size={17}/> Open Tournament Manager</Link></div><div className="quick-stats"><div><b>Gaming</b><small>Competitive content</small></div><div><b>Live</b><small>Streams & events</small></div><div><b>TGS</b><small>Community hub</small></div></div></div><div className="hero-art"><div className="orb-a"/><div className="car-card"><div className="car-glow">🏎️</div><span>ASPHALT LEGENDS</span><b>RACE NIGHT</b><small>Join the next TGS event</small></div><div className="floating-card"><Trophy size={16}/><span><b>TGS CLASH</b><small>Competitive event hub</small></span></div></div></section>
<section className="section" id="games"><div className="section-head"><div><span className="eyebrow">THE PLAYGROUND</span><h2>Games I play</h2></div><a className="text-link" href={YT} target="_blank" rel="noreferrer">View channel <ArrowRight size={14}/></a></div><div className="game-grid">{GAMES.map(([n,d,e])=><a className="game-card" href={YT} target="_blank" rel="noreferrer" key={n}><span className="game-emoji">{e}</span><div><h3>{n}</h3><p>{d}</p></div><ChevronRight size={17}/></a>)}</div></section>
<section className="feature-banner"><div><span className="eyebrow">BUILT FOR TGS</span><h2>Run tournaments without leaving the community.</h2><p>Create events, manage players, generate fixtures, record scores and view reports from one control center.</p></div><Link className="primary" to="/tournaments">Launch Tournament Manager <ArrowRight size={16}/></Link></section>
<section className="section" id="community"><div className="section-head"><div><span className="eyebrow">JOIN THE CREW</span><h2>Community & live action</h2></div></div><div className="community-grid"><a className="community-card" href={YT} target="_blank" rel="noreferrer"><Youtube/><div><b>YouTube</b><span>Videos & live gameplay</span></div><ArrowRight/></a><a className="community-card" href={YT} target="_blank" rel="noreferrer"><MessageCircle/><div><b>Discord</b><span>TGS community</span></div><ArrowRight/></a><a className="community-card" href="https://github.com/techgurusumit" target="_blank" rel="noreferrer"><Github/><div><b>GitHub</b><span>TGS projects & tools</span></div><ArrowRight/></a></div></section>
<section className="section" id="about"><div className="about-card"><span className="eyebrow">ABOUT TGS</span><h2>Gaming, competition and community.</h2><p>Tech Guru Sumit is a gaming creator hub focused on live gameplay, racing games, community events and competitive tournaments.</p><div className="about-pills"><span><Gamepad2 size={14}/> Gaming content</span><span><Swords size={14}/> Competitive events</span><span><Users size={14}/> Community</span></div></div></section>
<footer><div className="brand"><span className="brand-badge">TGS</span><span><b>Tech Guru Sumit</b><small>© 2026 TGS Gaming Hub</small></span></div><div className="footer-links"><a href={YT} target="_blank" rel="noreferrer">YouTube</a><Link to="/tournaments">Tournament Manager</Link><a href="https://github.com/techgurusumit" target="_blank" rel="noreferrer">GitHub</a></div></footer></div>}

function Dashboard({ts,onCreate,onAction}){const p=[...new Set(ts.flatMap(t=>t.players))].length,m=ts.reduce((a,t)=>a+t.fixtures.length,0);return <div className="tm-page"><div className="tm-hero"><div><span className="eyebrow">TGS ESPORTS / CONTROL CENTER</span><h1>Run every tournament from one place.</h1><p>Create events, manage players, generate brackets, score matches and keep records.</p></div><div className="tm-hero-icon"><Trophy/></div></div><div className="tm-stats"><div><Users/><b>{p}</b><span>Players</span></div><div><Trophy/><b>{ts.length}</b><span>Tournaments</span></div><div><Swords/><b>{m}</b><span>Fixtures</span></div><div><BarChart3/><b>{ts.filter(t=>t.status==="Live").length}</b><span>Live Events</span></div></div><div className="panel"><div className="panel-head"><div><h2>Recent tournaments</h2><small>Manage your event history</small></div><button className="primary mini" onClick={onCreate}><Plus size={14}/> Create</button></div>{ts.map(t=><div className="t-row" key={t.id}><div className="t-icon"><Gamepad2 size={17}/></div><div className="t-main"><b>{t.name}</b><span>{t.game} • {t.format}</span></div><span className={"status "+status(t.status)}>{t.status}</span><div className="row-actions"><button onClick={()=>onAction("edit",t)}><Pencil size={14}/></button><button onClick={()=>onAction("delete",t)}><Trash2 size={14}/></button></div></div>)}</div></div>}

function List({ts,onCreate,onAction,onMatches}){return <div className="tm-page"><div className="panel-head list-title"><div><h2>All tournaments</h2><small>{ts.length} saved events</small></div><button className="primary mini" onClick={onCreate}><Plus size={14}/> New tournament</button></div><div className="tournament-cards">{ts.map(t=><article className="t-card" key={t.id}><div className="card-line"><span className="status-dot"/><span className={"status "+status(t.status)}>{t.status}</span></div><h3>{t.name}</h3><p>{t.game} • {t.format}</p><div className="meta"><span><Users size={13}/> {t.players.length} players</span><span><CalendarDays size={13}/> {t.date}</span></div><div className="card-buttons"><button onClick={()=>onMatches(t)}><Swords size={14}/> Matches</button><button onClick={()=>onAction("edit",t)}><Pencil size={14}/> Edit</button><button className="danger" onClick={()=>onAction("delete",t)}><Trash2 size={14}/> Delete</button></div></article>)}</div></div>}

function Players({ts}){const ps=[...new Set(ts.flatMap(t=>t.players))].filter(Boolean);return <div className="tm-page"><div className="panel-head"><div><h2>Players</h2><small>Players across all tournaments</small></div></div><div className="player-grid">{ps.map((p,i)=><div className="player-card" key={p}><span>{String(i+1).padStart(2,"0")}</span><div><b>{p}</b><small>{ts.filter(t=>t.players.includes(p)).length} tournament(s)</small></div></div>)}</div></div>}

function KnockoutBracket({t,onSave}){const rounds=[...new Set(t.fixtures.map(f=>f.round))].sort((a,b)=>a-b);const grouped=rounds.map(r=>({round:r,label:t.fixtures.find(f=>f.round===r)?.roundLabel||"Round",items:t.fixtures.filter(f=>f.round===r).sort((a,b)=>a.position-b.position)}));const score=(f,w)=>onSave(f,w);return <div className="bracket-wrap"><div className="bracket" style={{'--rounds':grouped.length}}>{grouped.map((g,ri)=><div className={ri>0?"bracket-round later":"bracket-round"} key={g.round}><div className="bracket-round-title">{g.label}</div><div className="bracket-stack">{g.items.map(f=><div className={"bracket-slot r"+ri} key={f.id}><div className="bracket-match"><div className="bracket-player">{f.p1||"TBD"}<select value={f.winner||""} onChange={e=>score(f,e.target.value)} aria-label={"Winner for "+(f.p1||"TBD")}>{<option value="">Winner</option>}{[f.p1,f.p2].filter(Boolean).map(p=><option key={p}>{p}</option>)}</select></div><div className="bracket-player">{f.p2||"TBD"}</div></div></div>)}</div></div>)}</div></div>}
function Matches({ts,selected,setTs,notify}){const[tid,setTid]=useState(selected?.id||ts[0]?.id),t=ts.find(x=>x.id===tid);if(!t)return <div className="empty">Create a tournament first.</div>;const save=(f,w)=>{const winner=w||"";const updated=ts.map(x=>{if(x.id!==t.id)return x;let fixtures=x.fixtures.map(v=>v.id===f.id?{...v,winner}:v);if(winner){fixtures=fixtures.map(v=>{if(v.round===f.round+1){const slot=Math.floor(f.position/2);const side=f.position%2;return v.position===slot?{...v,[side===0?"p1":"p2"]:winner}:v}return v})}return {...x,status:"Live",fixtures}});setTs(updated);notify(winner?"Match winner recorded.":"Winner cleared.")};const isKnockout=["Single Elimination","Double Elimination"].includes(t.format);return <div className="tm-page"><div className="panel-head"><div><h2>Matches & Fixtures</h2><small>Bracket view • {t.format}</small></div><select value={tid||""} onChange={e=>setTid(Number(e.target.value))}>{ts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>{t.fixtures.length?(isKnockout?<KnockoutBracket t={t} onSave={save}/>:<div className="fixture-list">{t.fixtures.map(f=><div className="fixture" key={f.id}><div><span>{f.roundLabel}</span><b>{f.p1||"TBD"} <em>vs</em> {f.p2||"TBD"}</b></div><select value={f.winner||""} onChange={e=>save(f,e.target.value)}><option value="">Winner</option>{[f.p1,f.p2].filter(Boolean).map(p=><option key={p}>{p}</option>)}</select></div>)}</div>):<div className="empty"><ClipboardList size={38}/><h3>No fixtures yet</h3><p>Generate fixtures from the tournament action flow.</p></div>}</div>}

function Reports({ts}){return <div className="tm-page"><div className="panel-head"><div><h2>Reports</h2><small>Tournament-wise and player activity</small></div></div><div className="report-grid">{ts.map(t=><div className="report-card" key={t.id}><span className={"status "+status(t.status)}>{t.status}</span><h3>{t.name}</h3><p>{t.game} • {t.players.length} players • {t.fixtures.length} fixtures</p><div className="report-numbers"><div><b>{t.players.length}</b><small>Players</small></div><div><b>{t.fixtures.length}</b><small>Matches</small></div><div><b>{t.fixtures.filter(x=>x.winner).length}</b><small>Scored</small></div></div></div>)}</div></div>}

function TournamentModal({initial,onClose,onSave}){const[name,setName]=useState(initial?.name||""),[game,setGame]=useState(initial?.game||"Asphalt Legends"),[format,setFormat]=useState(initial?.format||"Single Elimination"),[date,setDate]=useState(initial?.date||"20 Sep 2026"),[players,setPlayers]=useState((initial?.players||[""]).join("\n")),[pe,setPe]=useState(initial?.passwordEnabled||false),[pw,setPw]=useState(initial?.password||"");return <div className="modal-bg"><div className="modal"><div className="modal-head"><div><h2>{initial?"Update":"Create"} tournament</h2><p>Configure event, format and player roster.</p></div><button onClick={onClose}><X/></button></div><label>Tournament name<input value={name} onChange={e=>setName(e.target.value)} placeholder="TGS Clash #3"/></label><div className="two-input"><label>Game<select value={game} onChange={e=>setGame(e.target.value)}>{GAMES.map(g=><option key={g[0]}>{g[0]}</option>)}</select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}>{FORMATS.map(f=><option key={f}>{f}</option>)}</select></label></div><label>Date<input value={date} onChange={e=>setDate(e.target.value)}/></label><label>Players <small>One player per line</small><textarea rows="6" value={players} onChange={e=>setPlayers(e.target.value)}/></label><div className="password-toggle"><label className="check"><input type="checkbox" checked={pe} onChange={e=>setPe(e.target.checked)}/> Password protect edit / delete actions</label>{pe&&<input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="Tournament password"/>}</div><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave({...initial,name,game,format,date,players:clean(players.split("\n")),passwordEnabled:pe,password:pw,status:initial?.status||"Upcoming",fixtures:initial?.fixtures||[]})}>{initial?"Update":"Create"} Tournament</button></div></div></div>}

function PasswordModal({action,t,onClose,onPass}){const[p,setP]=useState("");return <div className="modal-bg"><div className="modal small"><div className="modal-head"><div><h2><LockKeyhole size={18}/> Password required</h2><p>{action} “{t.name}”</p></div><button onClick={onClose}><X/></button></div><input autoFocus type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="Tournament password"/><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onPass(p)}>Continue</button></div></div></div>}

function TM(){const[tab,setTab]=useState("dashboard"),[ts,setTs]=useState(()=>{try{return JSON.parse(localStorage.getItem("tgs_tournaments"))||SEED}catch{return SEED}}),[modal,setModal]=useState(null),[selected,setSelected]=useState(null),[guard,setGuard]=useState(null),[toast,setToast]=useState("");const persist=v=>{setTs(v);localStorage.setItem("tgs_tournaments",JSON.stringify(v))},notify=m=>{setToast(m);setTimeout(()=>setToast(""),2500)},action=(a,t)=>{if(t.passwordEnabled)setGuard({action:a,t});else exec(a,t)},exec=(a,t)=>{if(a==="delete"){persist(ts.filter(x=>x.id!==t.id));notify("Tournament deleted.")}else if(a==="edit"){setSelected(t);setModal("edit")}},create=t=>{persist([{...t,id:Date.now(),fixtures:[]},...ts]);setModal(null);notify("Tournament created.")},update=t=>{persist(ts.map(x=>x.id===t.id?t:x));setModal(null);notify("Tournament updated.")};return <div className="tm-shell"><aside className="tm-side"><Link to="/" className="tm-brand"><span className="brand-badge">TGS</span><span><b>Tournament Manager</b><small>Tech Guru Sumit</small></span></Link><p className="side-label">MANAGEMENT</p>{[["dashboard","Dashboard",BarChart3],["tournaments","Tournaments",Trophy],["players","Players",Users],["matches","Matches",Swords],["reports","Reports",BarChart3]].map(([k,l,I])=><button className={tab===k?"side-link active":"side-link"} key={k} onClick={()=>setTab(k)}><I size={17}/>{l}</button>)}<div className="side-grow"/><Link className="side-link" to="/"><Globe2 size={17}/>Back to Website</Link></aside><main className="tm-main"><header className="tm-top"><div><span className="eyebrow">TGS ESPORTS / CONTROL CENTER</span><h1>{tab}</h1></div><button className="primary" onClick={()=>setModal("create")}><Plus size={17}/> Create Tournament</button></header>{toast&&<div className="toast">{toast}</div>}{tab==="dashboard"&&<Dashboard ts={ts} onCreate={()=>setModal("create")} onAction={action}/>} {tab==="tournaments"&&<List ts={ts} onCreate={()=>setModal("create")} onAction={action} onMatches={t=>{setSelected(t);setTab("matches")}}/>}{tab==="players"&&<Players ts={ts}/>} {tab==="matches"&&<Matches ts={ts} selected={selected} setTs={persist} notify={notify}/>} {tab==="reports"&&<Reports ts={ts}/>}</main>{modal==="create"&&<TournamentModal onClose={()=>setModal(null)} onSave={create}/>} {modal==="edit"&&selected&&<TournamentModal initial={selected} onClose={()=>setModal(null)} onSave={update}/>} {guard&&<PasswordModal action={guard.action} t={guard.t} onClose={()=>setGuard(null)} onPass={p=>{if(p===guard.t.password){const g=guard;setGuard(null);exec(g.action,g.t)}else notify("Incorrect tournament password.")}}/>}</div>}
export default function App(){return window.location.pathname.startsWith("/tournaments")?<TM/>:<Home/>}