import React from 'react';
import ReactDOM from 'react-dom/client';
import { Trophy, Users, Swords, BarChart3, Settings, Plus, ArrowRight, CalendarDays, Gamepad2, Crown, LogIn, LogOut, Moon, Sun, X, Trash2, Pencil, GitBranch, Lock, CheckCircle2 } from 'lucide-react';
import './styles.css';

type Fixture={id:number;round:string;player1:string;player2:string;score1?:number;score2?:number;winner?:string};
type Tournament={id:number;name:string;game:string;format:string;players:number;playerNames:string[];status:'Live'|'Upcoming'|'Completed';date:string;password:string;passwordEnabled:boolean;fixtures:Fixture[]};
type User={name:string;email:string;password:string};

const sample:Tournament[]=[
 {id:1,name:'TGS Clash #2',game:'Asphalt Legends',format:'1v1 Knockout',players:16,playerNames:Array.from({length:16},(_,i)=>`Player ${i+1}`),status:'Completed',date:'13 Sep 2026',password:'',passwordEnabled:false,fixtures:[]},
 {id:2,name:'Death Race: Chapter 4',game:'Asphalt Legends',format:'Knockout',players:32,playerNames:Array.from({length:32},(_,i)=>`Player ${i+1}`),status:'Completed',date:'09 Aug 2026',password:'',passwordEnabled:false,fixtures:[]},
 {id:3,name:'TGS Community Cup',game:'Subway Surfers',format:'Points League',players:12,playerNames:Array.from({length:12},(_,i)=>`Player ${i+1}`),status:'Upcoming',date:'20 Sep 2026',password:'',passwordEnabled:false,fixtures:[]}
];

function normalize(t:any):Tournament{
 const count=Math.max(2,Number(t.players)||2);
 const names=Array.isArray(t.playerNames)&&t.playerNames.length?t.playerNames.slice(0,count):Array.from({length:count},(_,i)=>`Player ${i+1}`);
 while(names.length<count)names.push(`Player ${names.length+1}`);
 const protectedTournament=t.passwordEnabled===true&&typeof t.password==='string'&&t.password.length>0;
 return {...t,players:count,playerNames:names,password:protectedTournament?t.password:'',passwordEnabled:protectedTournament,fixtures:Array.isArray(t.fixtures)?t.fixtures:[]};
}
function loadTournaments():Tournament[]{
 try{const raw=localStorage.getItem('tgs_tournaments');if(!raw)return sample;const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed.map(normalize):sample}catch{return sample}
}
function makeFixtures(names:string[]):Fixture[]{const out:Fixture[]=[];for(let i=0;i<names.length;i+=2)out.push({id:Date.now()+i,round:'Round 1',player1:names[i],player2:names[i+1]||'BYE'});return out}
function uniquePlayers(ts:Tournament[]){return Array.from(new Set(ts.flatMap(t=>t.playerNames.map(p=>p.trim()).filter(Boolean))));}

function App(){
 const [active,setActive]=React.useState('Dashboard');
 const [tournaments,setTournaments]=React.useState<Tournament[]>(loadTournaments);
 const [user,setUser]=React.useState<User|null>(()=>{try{const s=localStorage.getItem('tgs_session');return s?JSON.parse(s):null}catch{return null}});
 const [authMode,setAuthMode]=React.useState<'login'|'register'>('login');
 const [theme,setTheme]=React.useState<'dark'|'light'>(()=>(localStorage.getItem('tgs_theme') as 'dark'|'light')||'dark');
 const [create,setCreate]=React.useState(false);const [edit,setEdit]=React.useState<Tournament|null>(null);const [playersEdit,setPlayersEdit]=React.useState<Tournament|null>(null);const [guard,setGuard]=React.useState<{action:'edit'|'delete'|'fixtures';t:Tournament}|null>(null);const [toast,setToast]=React.useState('');
 React.useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('tgs_theme',theme)},[theme]);
 React.useEffect(()=>{localStorage.setItem('tgs_tournaments',JSON.stringify(tournaments))},[tournaments]);
 const nav=[['Dashboard',BarChart3],['Tournaments',Trophy],['Players',Users],['Matches',Swords],['Reports',BarChart3]] as const;
 const logout=()=>{localStorage.removeItem('tgs_session');setUser(null);setAuthMode('login')};
 const executeAction=(action:'edit'|'delete'|'fixtures',t:Tournament)=>{
  if(action==='delete'){setTournaments(x=>x.filter(v=>v.id!==t.id));setToast('Tournament deleted.');}
  else if(action==='edit')setEdit(t);
  else{const fixtures=makeFixtures(t.playerNames);setTournaments(x=>x.map(v=>v.id===t.id?{...v,fixtures}:v));setActive('Matches');setToast('Fixtures created successfully.');}
 };
 const handleTournamentAction=(action:'edit'|'delete'|'fixtures',t:Tournament)=>{if(!t.passwordEnabled){executeAction(action,t);return}setGuard({action,t})};
 const checkPassword=(value:string)=>{if(!guard)return;const g=guard;if(value!==g.t.password){setToast('Incorrect tournament password.');return}setGuard(null);executeAction(g.action,g.t)};
 if(!user)return <AuthScreen mode={authMode} setMode={setAuthMode} onLogin={u=>{setUser(u);localStorage.setItem('tgs_session',JSON.stringify(u))}}/>;
 const activePlayers=uniquePlayers(tournaments);
 const totalMatches=tournaments.reduce((n,t)=>n+t.fixtures.length,0);
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">TGS</div><div><strong>Tournament Manager</strong><span>Tech Guru Sumit</span></div></div><div className="side-section-title">MANAGEMENT</div><nav>{nav.map(([label,Icon])=><button key={label} className={`nav-item ${active===label?'active':''}`} onClick={()=>{setActive(label);setToast('')}}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-spacer"/><button className={`nav-item ${active==='Settings'?'active':''}`} onClick={()=>setActive('Settings')}><Settings size={18}/><span>Settings</span></button><div className="profile-mini"><div className="avatar">{user.name[0]?.toUpperCase()}</div><div><strong>{user.name}</strong><span>{user.email}</span></div><button className="icon-btn" onClick={logout} title="Logout"><LogOut size={15}/></button></div></aside>
  <main className="main-content"><header className="topbar"><div><p className="eyebrow">TGS ESPORTS / CONTROL CENTER</p><h1>{active}</h1></div><div className="top-actions"><button className="theme-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}<span>{theme==='dark'?'Light':'Dark'} theme</span></button><button className="primary-btn" onClick={()=>setCreate(true)}><Plus size={18}/> Create Tournament</button></div></header>{toast&&<div className="toast">{toast}</div>}
   {active==='Dashboard'&&<Dashboard tournaments={tournaments} players={activePlayers.length} matches={totalMatches} onCreate={()=>setCreate(true)} onNavigate={setActive}/>} 
   {active==='Tournaments'&&<TournamentList tournaments={tournaments} onCreate={()=>setCreate(true)} onAction={handleTournamentAction}/>} 
   {active==='Players'&&<PlayersPage tournaments={tournaments} onEdit={setPlayersEdit}/>} 
   {active==='Matches'&&<MatchesPage tournaments={tournaments} onUpdate={(id,fixture)=>setTournaments(ts=>ts.map(t=>t.id===id?{...t,fixtures:t.fixtures.map(f=>f.id===fixture.id?fixture:f)}:t))}/>} 
   {active==='Reports'&&<Reports tournaments={tournaments}/>} 
   {active==='Settings'&&<SettingsPage theme={theme} setTheme={setTheme} user={user} logout={logout}/>} 
  </main>
  {create&&<CreateModal close={()=>setCreate(false)} save={t=>{setTournaments(x=>[{...t,id:Date.now()},...x]);setCreate(false);setActive('Tournaments');setToast('Tournament created. Password protection enabled.')}}/>}
  {edit&&<EditModal tournament={edit} close={()=>setEdit(null)} save={t=>{setTournaments(x=>x.map(v=>v.id===t.id?t:v));setEdit(null);setToast('Tournament updated successfully.')}}/>}
  {playersEdit&&<PlayersModal tournament={playersEdit} close={()=>setPlayersEdit(null)} save={t=>{setTournaments(x=>x.map(v=>v.id===t.id?t:v));setPlayersEdit(null);setToast('Player list updated successfully.')}}/>}
  {guard&&<PasswordModal action={guard.action} tournament={guard.t} close={()=>setGuard(null)} verify={checkPassword}/>} 
 </div>;
}

function Dashboard({tournaments,players,matches,onCreate,onNavigate}:{tournaments:Tournament[];players:number;matches:number;onCreate:()=>void;onNavigate:(x:string)=>void}){return <>
 <section className="hero-card"><div><span className="badge"><Gamepad2 size={14}/> Tournament Control</span><h2>Run every tournament from one place.</h2><p>Create tournaments, protect them with passwords, generate fixtures and manage your event history.</p></div><div className="hero-icon"><Trophy size={54}/></div></section>
 <section className="stats-grid"><Stat label="Total Tournaments" value={String(tournaments.length)} helper="Across all games" icon={<Trophy size={20}/>} onClick={()=>onNavigate('Tournaments')}/><Stat label="Active Players" value={String(players)} helper="Unique registered players" icon={<Users size={20}/>} onClick={()=>onNavigate('Players')}/><Stat label="Matches Recorded" value={String(matches)} helper="Generated fixtures" icon={<Swords size={20}/>} onClick={()=>onNavigate('Matches')}/><Stat label="Completed" value={String(tournaments.filter(t=>t.status==='Completed').length)} helper="Tournament history" icon={<Crown size={20}/>} onClick={()=>onNavigate('Reports')}/></section>
 <section className="section-block"><div className="section-head"><div><h3>Recent tournaments</h3><p>Open Tournaments to update, delete or create fixtures.</p></div><button className="text-btn" onClick={()=>onNavigate('Tournaments')}>View all <ArrowRight size={16}/></button></div><div className="tournament-grid">{tournaments.slice(0,6).map(t=><TournamentCard key={t.id} t={t}/>)}</div></section>
 <section className="section-block two-col"><div className="panel"><div className="section-head"><div><h3>Quick actions</h3><p>All actions are connected.</p></div></div><div className="quick-actions"><button onClick={onCreate}><Plus size={18}/><span><b>Create tournament</b><small>Set a tournament password</small></span></button><button onClick={()=>onNavigate('Players')}><Users size={18}/><span><b>Manage players</b><small>View and edit player lists</small></span></button><button onClick={()=>onNavigate('Matches')}><Swords size={18}/><span><b>Update matches</b><small>Record scores and winners</small></span></button><button onClick={()=>onNavigate('Reports')}><BarChart3 size={18}/><span><b>View reports</b><small>Tournament and player history</small></span></button></div></div></section>
 </>}
function TournamentList({tournaments,onCreate,onAction}:{tournaments:Tournament[];onCreate:()=>void;onAction:(a:'edit'|'delete'|'fixtures',t:Tournament)=>void}){return <section className="section-block"><div className="section-head"><div><h3>All tournaments</h3><p>{tournaments.length} tournament records</p></div><button className="primary-btn" onClick={onCreate}><Plus size={17}/> New Tournament</button></div><div className="tournament-grid">{tournaments.map(t=><TournamentCard key={t.id} t={t} action={onAction}/>)}</div></section>}
function TournamentCard({t,action}:{t:Tournament;action?:((a:'edit'|'delete'|'fixtures',t:Tournament)=>void)}){return <article className="tournament-card"><div className="card-top"><div className="game-icon"><Gamepad2 size={19}/></div><span className={`status ${t.status.toLowerCase()}`}>{t.status}</span></div><h4>{t.name}</h4><p className="muted">{t.game} · {t.format}</p><div className="meta-row"><span><Users size={15}/> {t.playerNames.length} players</span><span><Swords size={15}/> {t.fixtures.length} matches</span><span><CalendarDays size={15}/> {t.date}</span></div>{action?<div className="card-actions"><button onClick={()=>action('fixtures',t)}><GitBranch size={15}/> Create Fixtures</button><button onClick={()=>action('edit',t)}><Pencil size={15}/> Update Tournament</button><button className="delete-action" onClick={()=>action('delete',t)}><Trash2 size={15}/> Delete</button></div>:<span className="muted">Open Tournaments for management actions</span>}</article>}
function Stat({label,value,helper,icon,onClick}:{label:string;value:string;helper:string;icon:React.ReactNode;onClick:()=>void}){return <button className="stat-card stat-clickable" onClick={onClick}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{helper}</small></div></button>}

function PlayersPage({tournaments,onEdit}:{tournaments:Tournament[];onEdit:(t:Tournament)=>void}){return <section className="section-block"><div className="section-head"><div><h3>Active Players</h3><p>Players registered in each tournament. Select Edit Players to change names.</p></div></div>{tournaments.length===0?<Empty title="No players yet" text="Create a tournament and add players to see them here." icon={<Users size={34}/>}/>:<div className="players-groups">{tournaments.map(t=><div className="panel" key={t.id}><div className="section-head"><div><h3>{t.name}</h3><p>{t.game} · {t.playerNames.length} players</p></div><button className="secondary-btn" onClick={()=>onEdit(t)}><Pencil size={15}/> Edit Players</button></div><div className="list-grid">{t.playerNames.map((p,i)=><div className="list-row" key={`${t.id}-${i}`}><span><b>#{i+1}</b> {p}</span><small className="muted">{t.status}</small></div>)}</div></div>)}</div>}</section>}
function PlayersModal({tournament,close,save}:{tournament:Tournament;close:()=>void;save:(t:Tournament)=>void}){const[names,setNames]=React.useState(tournament.playerNames);const[error,setError]=React.useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();const clean=names.map(x=>x.trim());if(clean.some(x=>!x))return setError('Every player name is required.');save({...tournament,playerNames:clean,players:clean.length})};return <Modal title="Edit Players" subtitle={`Update ${tournament.name} player names.`} close={close}><form onSubmit={submit}><div className="player-editor">{names.map((n,i)=><label key={i}>Player {i+1}<input value={n} onChange={e=>setNames(a=>a.map((x,j)=>j===i?e.target.value:x))}/></label>)}</div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn">Save Players</button></div></form></Modal>}

function MatchesPage({tournaments,onUpdate}:{tournaments:Tournament[];onUpdate:(id:number,f:Fixture)=>void}){const[open,setOpen]=React.useState<number|null>(null);return <section className="section-block"><div className="section-head"><div><h3>Match & Fixture Board</h3><p>Generated fixtures and score records for every tournament.</p></div></div>{tournaments.every(t=>t.fixtures.length===0)?<Empty title="No fixtures yet" text="Open Tournaments and press Create Fixtures on a tournament card." icon={<Swords size={34}/>}/>:tournaments.filter(t=>t.fixtures.length>0).map(t=><div className="panel fixture-panel" key={t.id}><div className="section-head"><div><h3>{t.name}</h3><p>{t.game} · {t.fixtures.length} matches</p></div></div>{t.fixtures.map((f,i)=><FixtureRow key={f.id} fixture={f} index={i} open={open===f.id} setOpen={x=>setOpen(x?f.id:null)} onSave={nf=>onUpdate(t.id,nf)}/>)}</div>)}</section>}
function FixtureRow({fixture,index,open,setOpen,onSave}:{fixture:Fixture;index:number;open:boolean;setOpen:(x:boolean)=>void;onSave:(f:Fixture)=>void}){const[s1,setS1]=React.useState(fixture.score1===undefined?'':String(fixture.score1));const[s2,setS2]=React.useState(fixture.score2===undefined?'':String(fixture.score2));const record=()=>{if(fixture.player2==='BYE'){onSave({...fixture,winner:fixture.player1,score1:1,score2:0});return}const a=Number(s1),b=Number(s2);if(!Number.isFinite(a)||!Number.isFinite(b)||s1===''||s2==='')return;onSave({...fixture,score1:a,score2:b,winner:a===b?undefined:a>b?fixture.player1:fixture.player2});setOpen(false)};return <div className="fixture-panel-row"><div className="fixture-row"><span>Match {index+1}</span><b>{fixture.player1}</b><em>{fixture.winner?<CheckCircle2 size={16}/>: 'vs'}</em><b>{fixture.player2}</b><button className="secondary-btn" onClick={()=>setOpen(!open)}>{fixture.winner?'Edit Score':'Record Score'}</button></div>{open&&<div className="score-editor"><label>{fixture.player1}<input type="number" min="0" value={s1} onChange={e=>setS1(e.target.value)}/></label><span>—</span><label>{fixture.player2}<input type="number" min="0" value={s2} onChange={e=>setS2(e.target.value)} disabled={fixture.player2==='BYE'}/></label><button className="primary-btn" onClick={record}>Save Result</button></div>}{fixture.winner&&<div className="winner-line">Winner: <b>{fixture.winner}</b> · {fixture.score1} - {fixture.score2}</div>}</div>}

function Reports({tournaments}:{tournaments:Tournament[]}){const players=uniquePlayers(tournaments);return <section className="section-block"><div className="section-head"><div><h3>Reports</h3><p>Tournament-wise and player-wise summary.</p></div></div><div className="settings-grid"><div className="panel"><h3>Tournament Reports</h3>{tournaments.map(t=><div className="list-row" key={t.id}><span><b>{t.name}</b><small className="muted">{t.game}</small></span><span>{t.playerNames.length} players · {t.fixtures.length} matches</span></div>)}</div><div className="panel"><h3>Player Summary</h3><p className="muted">{players.length} unique players across all tournaments.</p>{players.slice(0,50).map(p=><div className="list-row" key={p}><span>{p}</span><span className="muted">{tournaments.filter(t=>t.playerNames.includes(p)).length} tournament(s)</span></div>)}</div></div></section>}

function SettingsPage({theme,setTheme,user,logout}:{theme:'dark'|'light';setTheme:(x:'dark'|'light')=>void;user:User;logout:()=>void}){return <section className="settings-grid"><div className="panel"><h3>Appearance</h3><p className="muted">Change the dashboard theme instantly.</p><div className="theme-options"><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}><Moon size={18}/> Dark</button><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}><Sun size={18}/> Light</button></div></div><div className="panel"><h3>Account</h3><p className="muted">Signed in as <b>{user.name}</b></p><p className="muted">{user.email}</p><button className="danger-btn" onClick={logout}><LogOut size={16}/> Logout</button></div></section>}

function AuthScreen({mode,setMode,onLogin}:{mode:'login'|'register';setMode:(m:'login'|'register')=>void;onLogin:(u:User)=>void}){const[name,setName]=React.useState('');const[email,setEmail]=React.useState('');const[password,setPassword]=React.useState('');const[error,setError]=React.useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();const users:User[]=JSON.parse(localStorage.getItem('tgs_users')||'[]');if(!email||!password||(mode==='register'&&!name))return setError('Please fill all required fields.');if(mode==='register'){if(users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return setError('Account already exists.');const u={name,email,password};localStorage.setItem('tgs_users',JSON.stringify([...users,u]));onLogin(u)}else{const u=users.find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===password);if(!u)return setError('Invalid email or password.');onLogin(u)}};return <div className="auth-shell"><div className="auth-card"><div className="auth-brand"><div className="brand-mark">TGS</div><div><strong>TGS Tournament Manager</strong><span>Tech Guru Sumit</span></div></div><div className="auth-title"><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p>{mode==='login'?'Sign in to manage your tournaments.':'Register to start managing tournaments.'}</p></div><form onSubmit={submit}>{mode==='register'&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-btn auth-submit" type="submit">{mode==='login'?<><LogIn size={17}/> Login</>:'Register'}</button></form><button className="switch-auth" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?"Don't have an account? Register":'Already have an account? Login'}</button></div></div>}

function CreateModal({close,save}:{close:()=>void;save:(t:Omit<Tournament,'id'>)=>void}){const[name,setName]=React.useState('');const[game,setGame]=React.useState('Asphalt Legends');const[players,setPlayers]=React.useState(2);const[password,setPassword]=React.useState('');const[confirm,setConfirm]=React.useState('');const[error,setError]=React.useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return setError('Tournament name is required.');if(players<2||players>128)return setError('Players must be between 2 and 128.');if(password.length<4)return setError('Tournament password must be at least 4 characters.');if(password!==confirm)return setError('Passwords do not match.');save({name:name.trim(),game,format:'1v1 Knockout',players,playerNames:Array.from({length:players},(_,i)=>`Player ${i+1}`),status:'Upcoming',date:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),password,passwordEnabled:true,fixtures:[]})};return <Modal title="Create New Tournament" subtitle="Set a password now. It will be required for Update, Delete and Create Fixtures." close={close}><form onSubmit={submit}><label>Tournament Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. TGS Clash #3"/></label><label>Game<select value={game} onChange={e=>setGame(e.target.value)}><option>Asphalt Legends</option><option>Subway Surfers</option><option>Hill Climb Racing</option><option>Roblox</option><option>Minecraft</option><option>Other</option></select></label><label>Number of Players<input type="number" min="2" max="128" value={players} onChange={e=>setPlayers(Number(e.target.value))}/></label><label>Tournament Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 4 characters"/></label><label>Confirm Password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password"/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn"><Lock size={16}/> Create Tournament</button></div></form></Modal>}
function EditModal({tournament,close,save}:{tournament:Tournament;close:()=>void;save:(t:Tournament)=>void}){const[name,setName]=React.useState(tournament.name);const[game,setGame]=React.useState(tournament.game);const[password,setPassword]=React.useState('');const[error,setError]=React.useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return setError('Tournament name is required.');if(password!==tournament.password)return setError('Enter the current tournament password to save changes.');save({...tournament,name:name.trim(),game})};return <Modal title="Update Tournament" subtitle="Confirm the tournament password to save changes." close={close}><form onSubmit={submit}><label>Tournament Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Game<select value={game} onChange={e=>setGame(e.target.value)}><option>Asphalt Legends</option><option>Subway Surfers</option><option>Hill Climb Racing</option><option>Roblox</option><option>Minecraft</option><option>Other</option></select></label>{tournament.passwordEnabled&&<label>Tournament Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Current password"/></label>}{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn"><Pencil size={16}/> Save Changes</button></div></form></Modal>}
function PasswordModal({action,tournament,close,verify}:{action:'edit'|'delete'|'fixtures';tournament:Tournament;close:()=>void;verify:(p:string)=>void}){const[p,setP]=React.useState('');const title=action==='delete'?'Delete Tournament':action==='fixtures'?'Create Fixtures':'Update Tournament';return <Modal title={title} subtitle={`Enter the password for ${tournament.name}.`} close={close}><form onSubmit={e=>{e.preventDefault();verify(p)}}><label>Tournament Password<input autoFocus type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="Enter password"/></label><div className="password-warning"><Lock size={14}/> This action is protected by the tournament password.</div><div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn">Continue</button></div></form></Modal>}
function Modal({title,subtitle,close,children}:{title:string;subtitle:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="icon-btn" onClick={close}><X size={18}/></button></div>{children}</div></div>}
function Empty({title,text,icon}:{title:string;text:string;icon:React.ReactNode}){return <section className="empty-page"><div className="empty-icon">{icon}</div><h2>{title}</h2><p>{text}</p></section>}

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
