import React from 'react';
import ReactDOM from 'react-dom/client';
import { Trophy, Users, Swords, BarChart3, Settings, Plus, ArrowRight, CalendarDays, Gamepad2, Crown, LogIn, LogOut, Moon, Sun, X, Trash2, Pencil, GitBranch, Lock, ChevronDown, Search, Clock3, CheckCircle2 } from 'lucide-react';
import './styles.css';

type Fixture={id:number;roundIndex:number;round:string;position:number;player1?:string;player2?:string;pending1?:boolean;pending2?:boolean;score1?:number;score2?:number;winner?:string;dateTime?:string};
type Tournament={id:number;name:string;game:string;format:string;players:number;playerNames:string[];status:'Live'|'Upcoming'|'Completed';date:string;password:string;passwordEnabled:boolean;fixtures:Fixture[]};
type User={name:string;email:string;password:string};

const sample:Tournament[]=[
 {id:1,name:'TGS Clash #2',game:'Asphalt Legends',format:'1v1 Knockout',players:16,playerNames:Array.from({length:16},(_,i)=>`Player ${i+1}`),status:'Completed',date:'13 Sep 2026',password:'',passwordEnabled:false,fixtures:[]},
 {id:2,name:'Death Race: Chapter 4',game:'Asphalt Legends',format:'Knockout',players:32,playerNames:Array.from({length:32},(_,i)=>`Player ${i+1}`),status:'Completed',date:'09 Aug 2026',password:'',passwordEnabled:false,fixtures:[]},
 {id:3,name:'TGS Community Cup',game:'Subway Surfers',format:'Points League',players:12,playerNames:Array.from({length:12},(_,i)=>`Player ${i+1}`),status:'Upcoming',date:'20 Sep 2026',password:'',passwordEnabled:false,fixtures:[]}
];
function nextPowerOfTwo(n:number){let x=2;while(x<n)x*=2;return x}
function roundName(size:number,index:number){const remaining=size/Math.pow(2,index);if(remaining===2)return 'Final';if(remaining===4)return 'SF';if(remaining===8)return 'QF';return `R${remaining}`}
function makeBracket(names:string[]):Fixture[]{
 const clean=names.map(x=>x.trim()).filter(Boolean);const n=clean.length;const bracketSize=nextPowerOfTwo(Math.max(2,n));
 const hasPlayIn=n<bracketSize;const mainField=hasPlayIn?bracketSize/2:bracketSize;const playInCount=hasPlayIn?n-mainField:0;const out:Fixture[]=[];const stamp=Date.now();let roundIndex=0;
 if(playInCount>0){for(let p=0;p<playInCount;p++)out.push({id:stamp+p,roundIndex:0,round:'Play-In',position:p,player1:clean[p*2],player2:clean[p*2+1]});roundIndex=1}
 const direct=clean.slice(playInCount*2);
 for(let p=0;p<mainField/2;p++){const a=p*2,b=a+1;const f:Fixture={id:stamp+roundIndex*10000+p,roundIndex,round:roundName(mainField,0),position:p};if(a<playInCount)f.pending1=true;else f.player1=direct[a-playInCount];if(b<playInCount)f.pending2=true;else f.player2=direct[b-playInCount];out.push(f)}
 for(let r=1;r<Math.log2(mainField);r++){const count=mainField/Math.pow(2,r+1);for(let p=0;p<count;p++)out.push({id:stamp+(roundIndex+r)*10000+p,roundIndex:roundIndex+r,round:roundName(mainField,r),position:p})}
 return out;
}
function normalize(t:any):Tournament{const count=Math.max(2,Number(t.players)||2);const names=Array.isArray(t.playerNames)&&t.playerNames.length?t.playerNames.slice(0,count):Array.from({length:count},(_,i)=>`Player ${i+1}`);while(names.length<count)names.push(`Player ${names.length+1}`);const protectedTournament=t.passwordEnabled===true&&typeof t.password==='string'&&t.password.length>0;return {...t,players:count,playerNames:names,password:protectedTournament?t.password:'',passwordEnabled:protectedTournament,fixtures:Array.isArray(t.fixtures)?t.fixtures:[]}}
function loadTournaments():Tournament[]{try{const raw=localStorage.getItem('tgs_tournaments');if(!raw)return sample;const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed.map(normalize):sample}catch{return sample}}
function uniquePlayers(ts:Tournament[]){return Array.from(new Set(ts.flatMap(t=>t.playerNames.map(p=>p.trim()).filter(Boolean))))}

function App(){
 const [active,setActive]=React.useState('Dashboard');const [tournaments,setTournaments]=React.useState<Tournament[]>(loadTournaments);
 const [user,setUser]=React.useState<User|null>(()=>{try{const s=localStorage.getItem('tgs_session');return s?JSON.parse(s):null}catch{return null}});
 const [authMode,setAuthMode]=React.useState<'login'|'register'>('login');const [theme,setTheme]=React.useState<'dark'|'light'>((localStorage.getItem('tgs_theme') as any)||'dark');
 const [create,setCreate]=React.useState(false);const [edit,setEdit]=React.useState<Tournament|null>(null);const [playersEdit,setPlayersEdit]=React.useState<Tournament|null>(null);const [guard,setGuard]=React.useState<{action:'edit'|'delete'|'fixtures';t:Tournament}|null>(null);const [toast,setToast]=React.useState('');
 React.useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('tgs_theme',theme)},[theme]);React.useEffect(()=>{localStorage.setItem('tgs_tournaments',JSON.stringify(tournaments))},[tournaments]);
 const nav=[['Dashboard',BarChart3],['Tournaments',Trophy],['Players',Users],['Matches',Swords],['Reports',BarChart3]] as const;
 const logout=()=>{localStorage.removeItem('tgs_session');setUser(null);setAuthMode('login')};const updateTournament=(id:number,fn:(t:Tournament)=>Tournament)=>setTournaments(ts=>ts.map(t=>t.id===id?fn(t):t));
 const saveFixture=(id:number,f:Fixture)=>setTournaments(ts=>ts.map(t=>{if(t.id!==id)return t;const fixtures=t.fixtures.map(x=>x.id===f.id?f:{...x});if(f.winner){const next=fixtures.find(x=>x.roundIndex===f.roundIndex+1&&x.position===Math.floor(f.position/2));if(next){if(f.position%2===0){next.player1=f.winner;next.pending1=false}else{next.player2=f.winner;next.pending2=false}}}const final=fixtures.find(x=>x.round==='Final');return {...t,fixtures,status:final?.winner?'Completed':'Live'}}));
 const executeAction=(action:'edit'|'delete'|'fixtures',t:Tournament)=>{if(action==='delete'){setTournaments(x=>x.filter(v=>v.id!==t.id));setToast('Tournament deleted.');return}if(action==='edit'){setEdit(t);return}if(t.playerNames.filter(Boolean).length<2){setToast('Add at least 2 players before creating fixtures.');return}const fixtures=makeBracket(t.playerNames);updateTournament(t.id,v=>({...v,fixtures,status:'Live'}));setActive('Matches');setToast('Compact knockout bracket created from the participant count.');};
 const handleAction=(a:'edit'|'delete'|'fixtures',t:Tournament)=>{if(!t.passwordEnabled){executeAction(a,t);return}setGuard({action:a,t})};const checkPassword=(p:string)=>{if(!guard)return;if(p!==guard.t.password){setToast('Incorrect tournament password.');return}const g=guard;setGuard(null);executeAction(g.action,g.t)};
 if(!user)return <AuthScreen mode={authMode} setMode={setAuthMode} onLogin={u=>{setUser(u);localStorage.setItem('tgs_session',JSON.stringify(u))}}/>;
 const activePlayers=uniquePlayers(tournaments);const totalMatches=tournaments.reduce((n,t)=>n+t.fixtures.length,0);
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">TGS</div><div><strong>Tournament Manager</strong><span>Tech Guru Sumit</span></div></div><div className="side-section-title">MANAGEMENT</div><nav>{nav.map(([label,Icon])=><button key={label} className={`nav-item ${active===label?'active':''}`} onClick={()=>{setActive(label);setToast('')}}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-spacer"/><button className={`nav-item ${active==='Settings'?'active':''}`} onClick={()=>setActive('Settings')}><Settings size={18}/><span>Settings</span></button><div className="profile-mini"><div className="avatar">{user.name[0]?.toUpperCase()}</div><div><strong>{user.name}</strong><span>{user.email}</span></div><button className="icon-btn" onClick={logout} title="Logout"><LogOut size={15}/></button></div></aside>
  <main className="main-content"><header className="topbar"><div><p className="eyebrow">TGS ESPORTS / CONTROL CENTER</p><h1>{active}</h1></div><div className="top-actions"><button className="theme-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}<span>{theme==='dark'?'Light':'Dark'} theme</span></button><button className="primary-btn" onClick={()=>setCreate(true)}><Plus size={18}/> Create Tournament</button></div></header>{toast&&<div className="toast">{toast}</div>}
   {active==='Dashboard'&&<Dashboard tournaments={tournaments} players={activePlayers.length} matches={totalMatches} onCreate={()=>setCreate(true)} onNavigate={setActive}/>} {active==='Tournaments'&&<TournamentList tournaments={tournaments} onCreate={()=>setCreate(true)} onAction={handleAction}/>} {active==='Players'&&<PlayersPage tournaments={tournaments} onEdit={setPlayersEdit}/>} {active==='Matches'&&<MatchesPage tournaments={tournaments} onUpdate={saveFixture}/>} {active==='Reports'&&<Reports tournaments={tournaments}/>} {active==='Settings'&&<SettingsPage theme={theme} setTheme={setTheme} user={user} logout={logout}/>} 
  </main>
  {create&&<CreateModal close={()=>setCreate(false)} save={t=>{setTournaments(x=>[{...t,id:Date.now()},...x]);setCreate(false);setActive('Tournaments');setToast('Tournament created. Add player names from Players.')}}/>}{edit&&<EditModal tournament={edit} close={()=>setEdit(null)} save={t=>{setTournaments(x=>x.map(v=>v.id===t.id?t:v));setEdit(null);setToast('Tournament updated.')}}/>}{playersEdit&&<PlayersModal tournament={playersEdit} close={()=>setPlayersEdit(null)} save={t=>{setTournaments(x=>x.map(v=>v.id===t.id?t:v));setPlayersEdit(null);setToast('Player list updated.')}}/>}{guard&&<PasswordModal action={guard.action} tournament={guard.t} close={()=>setGuard(null)} verify={checkPassword}/>} 
 </div>;
}

function Dashboard({tournaments,players,matches,onCreate,onNavigate}:{tournaments:Tournament[];players:number;matches:number;onCreate:()=>void;onNavigate:(x:string)=>void}){return <><section className="hero-card"><div><span className="badge"><Gamepad2 size={14}/> Tournament Control</span><h2>Run every tournament from one place.</h2><p>Create tournaments, add players, generate a compact knockout bracket and record winners.</p></div><div className="hero-icon"><Trophy size={54}/></div></section><section className="stats-grid"><Stat label="Total Tournaments" value={String(tournaments.length)} helper="Across all games" icon={<Trophy size={20}/>} onClick={()=>onNavigate('Tournaments')}/><Stat label="Active Players" value={String(players)} helper="Unique registered players" icon={<Users size={20}/>} onClick={()=>onNavigate('Players')}/><Stat label="Matches Recorded" value={String(matches)} helper="Bracket fixtures" icon={<Swords size={20}/>} onClick={()=>onNavigate('Matches')}/><Stat label="Completed" value={String(tournaments.filter(t=>t.status==='Completed').length)} helper="Tournament history" icon={<Crown size={20}/>} onClick={()=>onNavigate('Reports')}/></section><section className="section-block"><div className="section-head"><div><h3>Recent tournaments</h3><p>Open Tournaments to manage players and create the bracket.</p></div><button className="text-btn" onClick={()=>onNavigate('Tournaments')}>View all <ArrowRight size={16}/></button></div><div className="tournament-grid">{tournaments.slice(0,6).map(t=><TournamentCard key={t.id} t={t}/>)}</div></section></>}
function TournamentList({tournaments,onCreate,onAction}:{tournaments:Tournament[];onCreate:()=>void;onAction:(a:'edit'|'delete'|'fixtures',t:Tournament)=>void}){return <section className="section-block"><div className="section-head"><div><h3>All tournaments</h3><p>{tournaments.length} tournament records</p></div><button className="primary-btn" onClick={onCreate}><Plus size={17}/> New Tournament</button></div><div className="tournament-grid">{tournaments.map(t=><TournamentCard key={t.id} t={t} action={onAction}/>)}</div></section>}
function TournamentCard({t,action}:{t:Tournament;action?:((a:'edit'|'delete'|'fixtures',t:Tournament)=>void)}){return <article className="tournament-card"><div className="card-top"><div className="game-icon"><Gamepad2 size={19}/></div><span className={`status ${t.status.toLowerCase()}`}>{t.status}</span></div><h4>{t.name}</h4><p className="muted">{t.game} · {t.format}</p><div className="meta-row"><span><Users size={15}/> {t.playerNames.length} players</span><span><Swords size={15}/> {t.fixtures.length} matches</span><span><CalendarDays size={15}/> {t.date}</span></div>{action?<div className="card-actions"><button onClick={()=>action('fixtures',t)}><GitBranch size={15}/> Create Fixtures</button><button onClick={()=>action('edit',t)}><Pencil size={15}/> Update</button><button className="delete-action" onClick={()=>action('delete',t)}><Trash2 size={15}/> Delete</button></div>:<span className="muted">Open Tournaments for management actions</span>}</article>}
function Stat({label,value,helper,icon,onClick}:{label:string;value:string;helper:string;icon:React.ReactNode;onClick:()=>void}){return <button className="stat-card stat-clickable" onClick={onClick}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{helper}</small></div></button>}
function PlayersPage({tournaments,onEdit}:{tournaments:Tournament[];onEdit:(t:Tournament)=>void}){const[q,setQ]=React.useState('');return <section className="section-block"><div className="section-head"><div><h3>Active Players</h3><p>Manage player names for each tournament before creating fixtures.</p></div><div className="search-box"><Search size={15}/><input placeholder="Search player" value={q} onChange={e=>setQ(e.target.value)}/></div></div>{tournaments.length===0?<Empty title="No players yet" text="Create a tournament first." icon={<Users size={34}/>}/>:<div className="players-groups">{tournaments.map(t=>{const names=t.playerNames.map((p,i)=>({p,i})).filter(x=>x.p.toLowerCase().includes(q.toLowerCase()));return <div className="panel" key={t.id}><div className="section-head"><div><h3>{t.name}</h3><p>{t.game} · {t.playerNames.length} players</p></div><button className="secondary-btn" onClick={()=>onEdit(t)}><Pencil size={15}/> Edit Players</button></div><div className="list-grid">{names.map(x=><div className="list-row" key={`${t.id}-${x.i}`}><span><b>#{x.i+1}</b> {x.p}</span><small className="muted">{t.status}</small></div>)}</div></div>})}</div>}</section>}
function PlayersModal({tournament,close,save}:{tournament:Tournament;close:()=>void;save:(t:Tournament)=>void}){const[names,setNames]=React.useState(tournament.playerNames);const[error,setError]=React.useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();const clean=names.map(x=>x.trim());if(clean.some(x=>!x))return setError('Every player name is required.');save({...tournament,playerNames:clean,players:clean.length,fixtures:[]})};return <Modal title="Edit Players" subtitle={`Enter players for ${tournament.name}. Fixtures reset when names change.`} close={close}><form onSubmit={submit}><div className="player-editor">{names.map((n,i)=><label key={i}>Player {i+1}<input value={n} onChange={e=>setNames(a=>a.map((x,j)=>j===i?e.target.value:x))}/></label>)}</div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn">Save Players</button></div></form></Modal>}
function MatchesPage({tournaments,onUpdate}:{tournaments:Tournament[];onUpdate:(id:number,f:Fixture)=>void}){const[selected,setSelected]=React.useState(tournaments.find(t=>t.fixtures.length)?.id||tournaments[0]?.id||0);const current=tournaments.find(t=>t.id===selected);return <section className="section-block"><div className="section-head"><div><h3>Auto Fixture Bracket</h3><p>Rounds and match count are generated from the number of participants.</p></div><div className="select-wrap"><ChevronDown size={15}/><select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{tournaments.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div></div>{!current||!current.fixtures.length?<Empty title="No fixtures yet" text="Go to Tournaments → Create Fixtures after entering player names." icon={<Swords size={34}/>}/>:<Bracket fixtures={current.fixtures} tournament={current} onUpdate={onUpdate}/>}</section>}
function Bracket({fixtures,tournament,onUpdate}:{fixtures:Fixture[];tournament:Tournament;onUpdate:(id:number,f:Fixture)=>void}){const rounds=Array.from(new Set(fixtures.map(f=>f.roundIndex))).sort((a,b)=>a-b);return <div className="bracket-shell"><div className="bracket-toolbar"><div><strong>{tournament.name}</strong><span>{tournament.game} · {tournament.playerNames.length} players · {fixtures.length} total matches</span></div><span className="bracket-note"><CheckCircle2 size={14}/> Winner auto-advances</span></div><div className="bracket-scroll"><div className="bracket">{rounds.map(r=><div className="bracket-round" key={r}><div className="round-title">{fixtures.find(f=>f.roundIndex===r)?.round||''}<span>{fixtures.filter(f=>f.roundIndex===r).length} matches</span></div><div className="round-matches">{fixtures.filter(f=>f.roundIndex===r).map(f=><BracketMatch key={f.id} fixture={f} onSave={nf=>onUpdate(tournament.id,nf)}/>)}</div></div>)}</div></div></div>}
function BracketMatch({fixture,onSave}:{fixture:Fixture;onSave:(f:Fixture)=>void}){const[p1,setP1]=React.useState(String(fixture.score1??''));const[p2,setP2]=React.useState(String(fixture.score2??''));const save=()=>{const a=p1===''?undefined:Number(p1),b=p2===''?undefined:Number(p2);if(a===undefined||b===undefined||a===b)return;const winner=a>b?fixture.player1:fixture.player2;if(!winner)return;onSave({...fixture,score1:a,score2:b,winner});};const waiting=Boolean(fixture.pending1||fixture.pending2||!fixture.player1||!fixture.player2);const p1Winner=Boolean(fixture.winner&&fixture.player1&&fixture.winner===fixture.player1);const p2Winner=Boolean(fixture.winner&&fixture.player2&&fixture.winner===fixture.player2);return <div className={`bracket-match ${fixture.winner?'won':''} ${waiting?'bye':''}`}><div className="match-head"><span>{fixture.round} · Game {fixture.position+1}</span><span>{fixture.dateTime?<><Clock3 size={11}/> {fixture.dateTime}</>:''}</span></div><div className={`player-line ${p1Winner?'winner':''}`}><b>{fixture.player1||'TBD'}</b>{!fixture.winner&&fixture.player1&&fixture.player2?<input className="inline-score-input" type="number" min="0" value={p1} onChange={e=>setP1(e.target.value)} placeholder="0"/>:<span>{fixture.score1??''}</span>}</div><div className={`player-line ${p2Winner?'winner':''}`}><b>{fixture.player2||'TBD'}</b>{!fixture.winner&&fixture.player1&&fixture.player2?<input className="inline-score-input" type="number" min="0" value={p2} onChange={e=>setP2(e.target.value)} placeholder="0"/>:<span>{fixture.score2??''}</span>}</div>{fixture.winner?<div className="winner-line"><CheckCircle2 size={12}/> {fixture.winner} advances</div>:waiting?<div className="winner-line">WAITING FOR OPPONENT</div>:<button className="inline-save-btn" onClick={save}>Save</button>}</div>}
function Reports({tournaments}:{tournaments:Tournament[]}){return <section className="section-block"><div className="section-head"><div><h3>Tournament Reports</h3><p>Overview of players, fixtures and results.</p></div></div><div className="reports-grid">{tournaments.map(t=><div className="panel" key={t.id}><div className="section-head"><div><h3>{t.name}</h3><p>{t.game}</p></div></div><div className="report-stats"><div><b>{t.playerNames.length}</b><span>Players</span></div><div><b>{t.fixtures.length}</b><span>Fixtures</span></div><div><b>{t.fixtures.filter(f=>f.winner).length}</b><span>Results</span></div></div></div>)}</div></section>}
function SettingsPage({theme,setTheme,user,logout}:{theme:'dark'|'light';setTheme:(x:'dark'|'light')=>void;user:User;logout:()=>void}){return <section className="settings-grid"><div className="panel"><h3>Appearance</h3><p className="muted">Change the dashboard theme instantly.</p><div className="theme-options"><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}><Moon size={18}/> Dark</button><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}><Sun size={18}/> Light</button></div></div><div className="panel"><h3>Account</h3><p className="muted">Signed in as <b>{user.name}</b></p><p className="muted">{user.email}</p><button className="danger-btn" onClick={logout}><LogOut size={16}/> Logout</button></div></section>}
function AuthScreen({mode,setMode,onLogin}:{mode:'login'|'register';setMode:(m:'login'|'register')=>void;onLogin:(u:User)=>void}){const[name,setName]=React.useState('');const[email,setEmail]=React.useState('');const[password,setPassword]=React.useState('');const[error,setError]=React.useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();const users:User[]=JSON.parse(localStorage.getItem('tgs_users')||'[]');if(!email||!password||(mode==='register'&&!name))return setError('Please fill all required fields.');if(mode==='register'){if(users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return setError('Account already exists.');const u={name,email,password};localStorage.setItem('tgs_users',JSON.stringify([...users,u]));onLogin(u)}else{const u=users.find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===password);if(!u)return setError('Invalid email or password.');onLogin(u)}};return <div className="auth-shell"><div className="auth-card"><div className="auth-brand"><div className="brand-mark">TGS</div><div><strong>TGS Tournament Manager</strong><span>Tech Guru Sumit</span></div></div><div className="auth-title"><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p>{mode==='login'?'Sign in to manage your tournaments.':'Register to start managing tournaments.'}</p></div><form onSubmit={submit}>{mode==='register'&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-btn auth-submit" type="submit">{mode==='login'?<><LogIn size={17}/> Login</>:'Register'}</button></form><button className="switch-auth" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?"Don't have an account? Register":'Already have an account? Login'}</button></div></div>}
function CreateModal({close,save}:{close:()=>void;save:(t:Omit<Tournament,'id'>)=>void}){const[name,setName]=React.useState('');const[game,setGame]=React.useState('Asphalt Legends');const[players,setPlayers]=React.useState(16);const[password,setPassword]=React.useState('');const[confirm,setConfirm]=React.useState('');const[error,setError]=React.useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return setError('Tournament name is required.');if(players<2)return setError('At least 2 players are required.');if(password.length<4)return setError('Tournament password must be at least 4 characters.');if(password!==confirm)return setError('Passwords do not match.');save({name:name.trim(),game,format:'1v1 Knockout',players,playerNames:Array.from({length:players},(_,i)=>`Player ${i+1}`),status:'Upcoming',date:new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),password,passwordEnabled:true,fixtures:[]})};return <Modal title="Create New Tournament" subtitle="Set the player count and password. Rename players before generating the bracket." close={close}><form onSubmit={submit}><label>Tournament Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. TGS Clash #3" autoFocus/></label><label>Game<select value={game} onChange={e=>setGame(e.target.value)}><option>Asphalt Legends</option><option>Subway Surfers</option><option>Hill Climb Racing</option><option>Roblox</option><option>Minecraft</option><option>Other</option></select></label><label>Number of Players<input type="number" min="2" value={players} onChange={e=>setPlayers(Math.max(2,Number(e.target.value)||2))}/></label><label><span className="password-label"><Lock size={13}/> Tournament Password *</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter tournament password"/></label><label><span className="password-label"><Lock size={13}/> Confirm Password *</span><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Re-enter password"/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button type="submit" className="primary-btn"><Lock size={15}/> Create Tournament</button></div></form></Modal>}
function EditModal({tournament,close,save}:{tournament:Tournament;close:()=>void;save:(t:Tournament)=>void}){const[name,setName]=React.useState(tournament.name);const[game,setGame]=React.useState(tournament.game);const[error,setError]=React.useState('');const submit=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return setError('Tournament name is required.');save({...tournament,name:name.trim(),game})};return <Modal title="Update Tournament" subtitle="Tournament password was already verified." close={close}><form onSubmit={submit}><label>Tournament Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Game<select value={game} onChange={e=>setGame(e.target.value)}><option>Asphalt Legends</option><option>Subway Surfers</option><option>Hill Climb Racing</option><option>Roblox</option><option>Minecraft</option><option>Other</option></select></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn"><Pencil size={15}/> Save Changes</button></div></form></Modal>}
function PasswordModal({action,tournament,close,verify}:{action:'edit'|'delete'|'fixtures';tournament:Tournament;close:()=>void;verify:(p:string)=>void}){const[p,setP]=React.useState('');const title=action==='edit'?'Update Tournament':action==='delete'?'Delete Tournament':'Create Fixtures';return <Modal title={title} subtitle={`Password required for: ${tournament.name}`} close={close}><form onSubmit={e=>{e.preventDefault();verify(p)}}><label><span className="password-label"><Lock size={13}/> Tournament Password</span><input type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="Enter tournament password" autoFocus/></label><div className="password-warning"><Lock size={15}/> Enter the password set for this tournament.</div><div className="modal-actions"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button type="submit" className={action==='delete'?'danger-btn':'primary-btn'}>{action==='delete'?<><Trash2 size={15}/> Confirm Delete</>:action==='edit'?<><Pencil size={15}/> Verify & Update</>:<><GitBranch size={15}/> Verify & Create</>}</button></div></form></Modal>}
function Modal({title,subtitle,close,children}:{title:string;subtitle:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="icon-btn" onClick={close}><X size={18}/></button></div>{children}</div></div>}
function Empty({title,text,icon}:{title:string;text:string;icon:React.ReactNode}){return <section className="empty-page"><div className="empty-icon">{icon}</div><h2>{title}</h2><p>{text}</p></section>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
